######################################################################
# Automatically generated by qmake (3.0) ?? 10? 17 21:06:11 2017
######################################################################

TEMPLATE = app
TARGET = SmartCar_Linux
INCLUDEPATH += .
QT += widgets core network

# Input
HEADERS += mainwindow.h
FORMS += login.ui \
    mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
